### PR TITLE
fix str() and repr() in python shell

### PR DESCRIPTION
**Pull request by ibizaman**
Maybe linked to #69 but I'm not sure.

### CODE REVIEW

**Comment by Psycojoker** [comment]
What is the bug here? How can I test it?

**Comment by Psycojoker** [comment]
Well, this PR breaks ipython syntaxe highlighting + ast node index displaying :/

**Comment by Psycojoker** [comment]
With your PR:
2015-06-22-124410_741x417_scrot

With master:
2015-06-22-124443_814x528_scrot

**Comment by ibizaman** [comment]
Well I see. I'll check what's going on - and why I needed this.

**Comment by ibizaman** [comment]
Let's close this. I have never been able to reproduce what I was doing...

**Pull request closed without merging**
